#!/usr/bin/env bash

SCRIPT_LOCATION=$(dirname ${BASH_SOURCE[0]})
REAL_LOCATION=$(cygpath -aw $SCRIPT_LOCATION)

PRE_COMMIT_CMD=$1
PRE_COMMIT_CONFIG_FILE=$REAL_LOCATION/pre-commit-config.yaml
shift

if [ x$MSYSTEM == xMINGW64 ]
then
    EXT=.exe
else
    EXT=
fi

$REAL_LOCATION/venv/Scripts/pre-commit$EXT $PRE_COMMIT_CMD -c $PRE_COMMIT_CONFIG_FILE $*



