repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.2
  hooks:
  - id: clang-format
- repo: https://gitea.strandkarr.net/christian/pre-commit-rust-format.git
  rev: v0.1.1
  hooks:
  - id: rust-format
