repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.2
  hooks:
  - id: clang-format
- repo: c:/home/yy11510/projects/adventofcode/resources/pre-commit/hooks/rust/
  rev: f10157474c510a197f504d6520b2d6797fe10246
  hooks:
  - id: rust-format
