CFLAGS = -g -I ../testlib -I../../include
LDLIBS = -laoc -laoctest
LDFLAGS = -L../../build/lib -L ../testlib

test_aoc_array: test_aoc_array.o aoc_test.o

run: 	test_aoc_array.exe
	@./test_aoc_array.exe

